from typing import Final


CATEGORY_NAMES: Final = {
    "en": {
        "sofas": "Sofas",
        "beds": "Beds",
        "wardrobes": "Wardrobes",
        "tables": "Tables",
        "chairs": "Chairs",
        "dressers": "Dressers",
    },
    "ru": {
        "sofas": "Диваны",
        "beds": "Кровати",
        "wardrobes": "Шкафы",
        "tables": "Столы",
        "chairs": "Стулья",
        "dressers": "Комоды",
    },
    "de": {
        "sofas": "Sofas",
        "beds": "Betten",
        "wardrobes": "Kleiderschränke",
        "tables": "Tische",
        "chairs": "Stühle",
        "dressers": "Kommoden",
    },
    "ja": {
        "sofas": "ソファ",
        "beds": "ベッド",
        "wardrobes": "ワードローブ",
        "tables": "テーブル",
        "chairs": "チェア",
        "dressers": "チェスト",
    },
    "fr": {
        "sofas": "Canapés",
        "beds": "Lits",
        "wardrobes": "Armoires",
        "tables": "Tables",
        "chairs": "Chaises",
        "dressers": "Commodes",
    },
}

CATEGORY_IMAGES: Final = {
    "sofas": "hero.jpg",
    "beds": "bed.jpg",
    "wardrobes": "wardrobe.jpg",
    "tables": "table.jpg",
    "chairs": "chair.jpg",
    "dressers": "dresser.jpg",
}

PRODUCT_TRANSLATIONS: Final = {
    1: {
        "en": {
            "name": "Lofty Sofa",
            "description": "A modular deep-seat sofa with soft textured upholstery.",
            "material": "Solid oak, bouclé",
            "size": "248 × 104 × 76 cm",
            "color": "Warm beige",
            "country": "Germany",
        },
        "ru": {
            "name": "Диван Lofty",
            "description": "Модульный глубокий диван с мягкой фактурной обивкой.",
            "material": "Массив дуба, букле",
            "size": "248 × 104 × 76 см",
            "color": "Тёплый бежевый",
            "country": "Германия",
        },
        "de": {
            "name": "Sofa Lofty",
            "description": "Ein modulares Sofa mit tiefer Sitzfläche und weichem Bouclé-Bezug.",
            "material": "Massive Eiche, Bouclé",
            "size": "248 × 104 × 76 cm",
            "color": "Warmes Beige",
            "country": "Deutschland",
        },
        "ja": {
            "name": "Lofty ソファ",
            "description": "柔らかな質感の張地と深い座面を備えたモジュール式ソファ。",
            "material": "オーク無垢材、ブークレ",
            "size": "248 × 104 × 76 cm",
            "color": "ウォームベージュ",
            "country": "ドイツ",
        },
        "fr": {
            "name": "Canapé Lofty",
            "description": "Un canapé modulaire à assise profonde et revêtement bouclé doux.",
            "material": "Chêne massif, bouclé",
            "size": "248 × 104 × 76 cm",
            "color": "Beige chaud",
            "country": "Allemagne",
        },
    },
    2: {
        "en": {
            "name": "Sense Bed",
            "description": "A natural oak bed with a flowing headboard and stable base.",
            "material": "Solid oak",
            "size": "160 × 200 cm",
            "color": "Natural oak",
            "country": "Germany",
        },
        "ru": {
            "name": "Кровать Sense",
            "description": "Кровать из натурального дуба с плавным изголовьем и устойчивым основанием.",
            "material": "Массив дуба",
            "size": "160 × 200 см",
            "color": "Натуральный дуб",
            "country": "Германия",
        },
        "de": {
            "name": "Bett Sense",
            "description": "Ein Bett aus natürlicher Eiche mit fließendem Kopfteil und stabilem Unterbau.",
            "material": "Massive Eiche",
            "size": "160 × 200 cm",
            "color": "Natureiche",
            "country": "Deutschland",
        },
        "ja": {
            "name": "Sense ベッド",
            "description": "流れるようなヘッドボードと安定した土台を備えた天然オークのベッド。",
            "material": "オーク無垢材",
            "size": "160 × 200 cm",
            "color": "ナチュラルオーク",
            "country": "ドイツ",
        },
        "fr": {
            "name": "Lit Sense",
            "description": "Un lit en chêne naturel avec tête fluide et base stable.",
            "material": "Chêne massif",
            "size": "160 × 200 cm",
            "color": "Chêne naturel",
            "country": "Allemagne",
        },
    },
    3: {
        "en": {
            "name": "Slide Wardrobe",
            "description": "A spacious wardrobe with a clean facade and thoughtful storage.",
            "material": "Oak veneer, MDF",
            "size": "180 × 60 × 220 cm",
            "color": "Honey oak",
            "country": "Germany",
        },
        "ru": {
            "name": "Шкаф Slide",
            "description": "Вместительный шкаф с лаконичным фасадом и продуманным хранением.",
            "material": "Шпон дуба, МДФ",
            "size": "180 × 60 × 220 см",
            "color": "Медовый дуб",
            "country": "Германия",
        },
        "de": {
            "name": "Kleiderschrank Slide",
            "description": "Ein geräumiger Kleiderschrank mit ruhiger Front und durchdachter Aufteilung.",
            "material": "Eichenfurnier, MDF",
            "size": "180 × 60 × 220 cm",
            "color": "Honigeiche",
            "country": "Deutschland",
        },
        "ja": {
            "name": "Slide ワードローブ",
            "description": "すっきりした外観と考え抜かれた収納を備えた広々としたワードローブ。",
            "material": "オーク突板、MDF",
            "size": "180 × 60 × 220 cm",
            "color": "ハニーオーク",
            "country": "ドイツ",
        },
        "fr": {
            "name": "Armoire Slide",
            "description": "Une armoire spacieuse à façade épurée et rangement bien pensé.",
            "material": "Placage chêne, MDF",
            "size": "180 × 60 × 220 cm",
            "color": "Chêne miel",
            "country": "Allemagne",
        },
    },
    4: {
        "en": {
            "name": "Frame Table",
            "description": "A dining table with an expressive top and a light silhouette.",
            "material": "Solid ash",
            "size": "180 × 90 × 75 cm",
            "color": "Walnut",
            "country": "Germany",
        },
        "ru": {
            "name": "Стол Frame",
            "description": "Обеденный стол с выразительной столешницей и лёгким силуэтом.",
            "material": "Массив ясеня",
            "size": "180 × 90 × 75 см",
            "color": "Орех",
            "country": "Германия",
        },
        "de": {
            "name": "Tisch Frame",
            "description": "Ein Esstisch mit ausdrucksstarker Platte und leichter Silhouette.",
            "material": "Massive Esche",
            "size": "180 × 90 × 75 cm",
            "color": "Walnuss",
            "country": "Deutschland",
        },
        "ja": {
            "name": "Frame テーブル",
            "description": "表情豊かな天板と軽やかなシルエットをもつダイニングテーブル。",
            "material": "アッシュ無垢材",
            "size": "180 × 90 × 75 cm",
            "color": "ウォールナット",
            "country": "ドイツ",
        },
        "fr": {
            "name": "Table Frame",
            "description": "Une table de repas au plateau expressif et à la silhouette légère.",
            "material": "Frêne massif",
            "size": "180 × 90 × 75 cm",
            "color": "Noyer",
            "country": "Allemagne",
        },
    },
    5: {
        "en": {
            "name": "Line Chair",
            "description": "An ergonomic chair with a soft back and solid wooden frame.",
            "material": "Solid ash, matting",
            "size": "48 × 54 × 82 cm",
            "color": "Tobacco",
            "country": "Germany",
        },
        "ru": {
            "name": "Стул Line",
            "description": "Эргономичный стул с мягкой спинкой и прочным деревянным каркасом.",
            "material": "Массив ясеня, рогожка",
            "size": "48 × 54 × 82 см",
            "color": "Табачный",
            "country": "Германия",
        },
        "de": {
            "name": "Stuhl Line",
            "description": "Ein ergonomischer Stuhl mit weicher Rückenlehne und massivem Holzrahmen.",
            "material": "Massive Esche, Strukturstoff",
            "size": "48 × 54 × 82 cm",
            "color": "Tabak",
            "country": "Deutschland",
        },
        "ja": {
            "name": "Line チェア",
            "description": "柔らかな背もたれと頑丈な木製フレームを備えた人間工学的なチェア。",
            "material": "アッシュ無垢材、織物",
            "size": "48 × 54 × 82 cm",
            "color": "タバコブラウン",
            "country": "ドイツ",
        },
        "fr": {
            "name": "Chaise Line",
            "description": "Une chaise ergonomique au dossier souple et à la structure en bois massif.",
            "material": "Frêne massif, tissu texturé",
            "size": "48 × 54 × 82 cm",
            "color": "Tabac",
            "country": "Allemagne",
        },
    },
    6: {
        "en": {
            "name": "Mod Dresser",
            "description": "A compact dresser with six soft-closing drawers.",
            "material": "Oak veneer, solid wood",
            "size": "120 × 45 × 78 cm",
            "color": "Natural oak",
            "country": "Germany",
        },
        "ru": {
            "name": "Комод Mod",
            "description": "Компактный комод с шестью ящиками плавного закрывания.",
            "material": "Шпон дуба, массив дерева",
            "size": "120 × 45 × 78 см",
            "color": "Натуральный дуб",
            "country": "Германия",
        },
        "de": {
            "name": "Kommode Mod",
            "description": "Eine kompakte Kommode mit sechs sanft schließenden Schubladen.",
            "material": "Eichenfurnier, Massivholz",
            "size": "120 × 45 × 78 cm",
            "color": "Natureiche",
            "country": "Deutschland",
        },
        "ja": {
            "name": "Mod チェスト",
            "description": "ソフトクローズ式の引き出しを6杯備えたコンパクトなチェスト。",
            "material": "オーク突板、無垢材",
            "size": "120 × 45 × 78 cm",
            "color": "ナチュラルオーク",
            "country": "ドイツ",
        },
        "fr": {
            "name": "Commode Mod",
            "description": "Une commode compacte avec six tiroirs à fermeture douce.",
            "material": "Placage chêne, bois massif",
            "size": "120 × 45 × 78 cm",
            "color": "Chêne naturel",
            "country": "Allemagne",
        },
    },
}

DEFAULT_PRODUCT_DATA: Final = {
    1: ("sofas", 59990, 98),
    2: ("beds", 45990, 94),
    3: ("wardrobes", 38990, 86),
    4: ("tables", 29990, 91),
    5: ("chairs", 9990, 80),
    6: ("dressers", 24990, 84),
}

SHIPPING_ZONE_NAMES: Final = {
    "local": {
        "en": "Regional delivery",
        "ru": "Региональная доставка",
        "de": "Regionale Lieferung",
        "ja": "地域配送",
        "fr": "Livraison régionale",
    },
    "international": {
        "en": "International delivery",
        "ru": "Международная доставка",
        "de": "Internationale Lieferung",
        "ja": "国際配送",
        "fr": "Livraison internationale",
    },
}
